### ISSUE TITLE
Timeout support (connect and execution)

### ISSUE THREAD

**Issue by Beanow** [reactphp/socket-client#28]
For comparison curl provides you with two options:
- `CURLOPT_CONNECTTIMEOUT` the time it may take to establish the connection.
- `CURLOPT_TIMEOUT` the time the total execution of the request is allowed to take.

Both of these I'm currently using to "probe" ~150 servers per day and test their connect and response time. Since this is about speed, I'm not interested in keeping the connection open for more than a couple of seconds, so I would like to tweak both these parameters.

The [timeout branch](https://github.com/reactphp/socket-client/blob/timeout/src/TimeoutTrait.php) seemed to be aimed at the total execution time equivalent.
And the connection timeout is available in [stream_socket_client](http://php.net/manual/en/function.stream-socket-client.php), currently a fixed value [Connector.php:43](https://github.com/reactphp/socket-client/blob/a91bb2f986c8e07674708aba75629c227db8c7b3/src/Connector.php#L43).

**Comment by afk11** [comment]
I think @clue's last post in #12 may provide a means to achieve this neatly. Otherwise, we're looking at a slate of reimplementations of the same logic. 

https://github.com/clue/php-redis-react/issues/10
https://github.com/reactphp/socket-client/pull/10
https://github.com/ratchetphp/Ratchet/issues/316
https://github.com/reactphp/whois/issues/3 (around since 2012)

**Comment by clue** [comment]
> Timeout support (connect and execution)

I'm all for adding support for connection timeout handling! :+1: 

However, I'm not sure how the "execution timeout" applies in the context of this library (rather low-level connection establishment). Can you explain what you're referring to with "execution" timeout (or "the time the total execution of the request is allowed to take").

> Issues of react end users regarding timeouts (there are bound to be more) […]

Indeed, there are quite a few open tickets that deal with connection timeouts (and probably many more we're not even aware of).

For this reason, I've started working on a very simple low-level timeout library (https://github.com/clue/php-promise-timeout). This library can easily be embedded in order to add timeout support to pretty much any Promise-based API.

In this particular case, here's a prototype for how this could be used in this library (dedicated `TimeoutConnector`): https://gist.github.com/clue/75d00d9c2ca2e931661c#file-timeoutconnector-php-L17

Open issue before I feel comfortable filing a PR is *where* this library should live. IMO it should be part of the ReactPHP namespace, so here's a ticket for discussing this further: https://github.com/clue/php-promise-timeout/issues/2

Any input is welcome!

**Comment by clue** [comment]
> Any input is welcome!

This ticket has been open for quite some time already :) The timeout handling is now part of the new [react/promise-timer component](https://github.com/reactphp/promise-timer#timeout), see also PR #51 which integrates this here.
