### ISSUE TITLE
Connection doesn't time out when using SSL

### ISSUE THREAD

**Issue by flip111** [reactphp/socket-client#55]
This is in support of https://github.com/phergie/phergie-irc-bot-react/issues/42 

i noticed the code never goes into this line https://github.com/reactphp/socket-client/blob/v0.4.4/src/SecureConnector.php#L22 because there is isn't a write event coming while it seems to be waiting for that https://github.com/reactphp/socket-client/blob/v0.4.4/src/Connector.php#L58

can someone confirm this and also explain why a write event is expected and what kind of write event is suppose to trigger this?

**Comment by clue** [comment]
> can someone confirm this […]

Yes, lack of proper timeout support is a [known issue](https://github.com/reactphp/socket-client/issues/28). Note however that this is unrelated to SSL/TLS, so in your case it looks like the underlying TCP/IP connection already times out.

FWIW: Your OS will likely still implement a timeout for the socket, though we currently offer no API to change this value. It will likely be anywhere between a few minutes or hours, which is likely way beyond what most applications want.

See also PR #51 for a possible implementation.

> explain why a write event is expected and what kind of write event is suppose to trigger this?

This is the normal async socket connection approach: Open the underlying socket resource, set it to non-blocking mode and start the connection. Once the socket descriptor becomes writable it means we can check if the connection has either been accepted or rejected.

Because we currently offer no custom timeout handling, we currently rely entirely on the OS timeout. This means the "write" event will actually trigger eventually, you're probably just not patient enough :-)

Let's look into finally getting #28/#51 in! :shipit:
